[package]
name = "adapter-graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-graphql = { version = "6.0.0", features = ["log", "dataloader"] }
async-trait = "0.1.72"
